# Generated by Django 5.2.5 on 2025-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='system_prompt',
            field=models.TextField(default='You are a helpful assistant providing accurate, concise responses.', help_text="System prompt that defines the AI assistant's behavior and personality"),
        ),
    ]
