# Generated by Django 5.2.6 on 2025-09-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chatbot', '0004_update_aicc_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotconfiguration',
            name='enable_query_rephrasing',
            field=models.BooleanField(default=True, help_text='Enable LLM-based query rephrasing for better retrieval on subsequent queries'),
        ),
        migrations.AlterField(
            model_name='chatbotconfiguration',
            name='default_model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotconfiguration',
            name='similarity_threshold',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='chatbotconfiguration',
            name='system_prompt',
            field=models.TextField(default='You are a helpful assistant providing accurate, concise responses.', help_text="System prompt that defines the AI assistant's behavior and personality"),
        ),
    ]
